### ISSUE TITLE
nakeskin -> Snakeskin

### ISSUE THREAD

**Issue by hcodes** [SnakeskinTpl/snakeskin.github.io#3]
![nakeskin](https://cloud.githubusercontent.com/assets/157520/18685634/9c58ab08-7f81-11e6-9c55-7d439385e54a.png)

Не могу себя заставить читать Snakeskin, получается nakeskin.

**Comment by hcodes** [comment]
Заодно, красная строка в документации в абзацах не нужна, так как есть отступ между ними.
Нужно использовать что-то одно.

**Comment by kobezzza** [comment]
PR welcome :)

**Comment by kobezzza** [comment]
Изменения накатились, спасибо за помощь! 👍 .
